<div class="header">
	<img src="/modules/header/view/img/logo.png" title="JJPaya Forums">
	<span class="nav">
		<a data-tr="p-main"    href="/main"    class="<?= $current_p('main', true); ?>"></a>
		<a data-tr="p-cars"    href="/cars"    class="<?= $current_p('cars'); ?>"></a>
		<a data-tr="p-about"   href="/about"   class="<?= $current_p('about'); ?>"></a>
		<a data-tr="p-contact" href="/contact" class="<?= $current_p('contact'); ?>"></a>
	</span>
	<span class="lang">
		<a data-tr-switch="es" href="#" title="ES">
			<img src="/modules/header/view/img/es.png" alt="ES">
		</a>
		<a data-tr-switch="en" href="#" title="EN">
			<img src="/modules/header/view/img/en.png" alt="EN">
		</a>
	</span>
</div>