<meta name="jjp-google-api" content="<?= Config::get_google_api_key() ?>"/>
<link rel="stylesheet" href="/modules_fe/page_shop/view/css/shop.css">
<link rel="stylesheet" href="/modules_fe/page_shop/view/css/shop_view.css">
<link rel="stylesheet" href="/modules_fe/page_shop/view/css/shop_details.css">
<script src="/modules_fe/page_shop/view/js/shop.js"></script>
<script async src="https://maps.googleapis.com/maps/api/js?key=<?= Config::get_google_api_key() ?>&callback=initMap"></script>
