<div class="page cars">
	<div class="card">
		<h2>Create car</h2>
		<hr>
		<p>Please fill out the form to create a new car listing:</p>
		<form id="car-f-form" method="post">
			<label>
				<span>Number Plate:</span>
				<input id="car-f-npl" required maxlength="7" type="text" name="num_plate"/>
				<span class="err-msg">The number plate must not be empty.</span>
			</label>
			
			<label>
				<span>Registration date:</span>
				<input id="car-f-rdat" required type="date" name="reg_date"/>
				<span class="err-msg">Must not be empty.</span>
			</label>
			
			<label>
				<span>Brand:</span>
				<select id="car-f-brn" required name="brand_id">
					<?php while ($brn = $next_brand()): ?>
						<option value="<?= $brn['brand_id'] ?>"><?= $brn['name'] ?></option>
					<?php endwhile; ?>
				</select>
				<span class="err-msg">Must select a brand.</span>
			</label>
			
			<label>
				<span>Model:</span>
				<input id="car-f-mdl" required maxlength="24" type="text" name="model"/>
				<span class="err-msg">Model must not be empty.</span>
			</label>
			
			<label>
				<span>Color:</span>
				<input id="car-f-clr" required type="color" name="color"/>
			</label>
			
			<label>
				<span>KMs:</span>
				<input id="car-f-kms" required min="0" max="999999" type="number" name="kms"/>
				<span class="err-msg">KM count must not be empty, and must be less than 999999.</span>
			</label>
			
			<label>
				<span>ITV:</span>
				<input id="car-f-itv" type="checkbox" name="itv"/>
			</label>
			
			<div>
				<span>Wheel Power:</span>
				<input id="car-f-wp-fr" type="radio" name="wheel_power" value="front"/>
				<label for="car-f-wp-fr">Front</label>
				
				<input id="car-f-wp-re" type="radio" name="wheel_power" value="rear"/>
				<label for="car-f-wp-re">Rear</label>
				
				<input id="car-f-wp-all" type="radio" name="wheel_power" value="all"/>
				<label for="car-f-wp-all">All</label>
			</div>
			
			<label>
				<span>Price:</span>
				<input id="car-f-pri" required min="10000" max="500000000" type="number" value="100000" step="10000" name="price_eur_cent"/>
				<span class="err-msg">Must have a price.</span>
			</label>
			
			<label>
				<span>Description:</span>
				<textarea id="car-f-desc" required maxlength="255" name="description"></textarea>
				<span class="err-msg">Description must not be empty.</span>
			</label>
			
			<div><input id="car-f-create" type="submit" value="Create"/></div>
		</form>
		<a href="/cars">Go back</a>
	</div>
</div>