<div class="page cars">
	<div class="card">
		<h2>Update car</h2>
		<hr>
		<p>Please edit out the form to modify car <?= $car['car_id'] ?>:</p>
		<form id="car-f-form" method="post">
			<label>
				<span>Number Plate:</span>
				<input id="car-f-npl" required maxlength="7" type="text" name="num_plate" value="<?= $car['num_plate'] ?>"/>
				<span class="err-msg">The number plate must not be empty.</span>
			</label>
			
			<label>
				<span>Registration date:</span>
				<input id="car-f-rdat" required type="date" name="reg_date" value="<?= $car['reg_date'] ?>"/>
				<span class="err-msg">Must not be empty.</span>
			</label>
			
			<label>
				<span>Brand:</span>
				<select id="car-f-brn" required name="brand_id">
					<?php while ($brn = $next_brand()): ?>
						<option value="<?= $brn['brand_id'] ?>" <?= ($car['brand_id'] === $brn['brand_id'] ? 'selected' : '') ?>><?= $brn['name'] ?></option>
					<?php endwhile; ?>
				</select>
				<span class="err-msg">Must select a brand.</span>
			</label>
			
			<label>
				<span>Model:</span>
				<input id="car-f-mdl" required maxlength="24" type="text" name="model" value="<?= $car['model'] ?>"/>
				<span class="err-msg">Model must not be empty.</span>
			</label>
			
			<label>
				<span>Color:</span>
				<input id="car-f-clr" required type="color" name="color" value="<?= $car['color'] ?>"/>
			</label>
			
			<label>
				<span>KMs:</span>
				<input id="car-f-kms" required min="0" max="999999" type="number" name="kms" value="<?= $car['kms'] ?>"/>
				<span class="err-msg">KM count must not be empty, and must be less than 999999.</span>
			</label>
			
			<label>
				<span>ITV:</span>
				<input id="car-f-itv" type="checkbox" name="itv" <?= ($car['itv'] === 1 ? 'checked' : '') ?>/>
			</label>
			
			<div>
				<span>Wheel Power:</span>
				<input id="car-f-wp-fr" type="radio" name="wheel_power" value="front" <?= ($car['wheel_power'] === 'front' ? 'checked' : '') ?>/>
				<label for="car-f-wp-fr">Front</label>
				
				<input id="car-f-wp-re" type="radio" name="wheel_power" value="rear" <?= ($car['wheel_power'] === 'rear' ? 'checked' : '') ?>/>
				<label for="car-f-wp-re">Rear</label>
				
				<input id="car-f-wp-all" type="radio" name="wheel_power" value="all" <?= ($car['wheel_power'] === 'all' ? 'checked' : '') ?>/>
				<label for="car-f-wp-all">All</label>
			</div>
			
			<label>
				<span>Price:</span>
				<input id="car-f-pri" required min="10000" max="500000000" type="number" value="100000" step="10000" name="price_eur_cent" value="<?= $car['price_eur_cent'] ?>"/>
				<span class="err-msg">Must have a price.</span>
			</label>
			
			<label>
				<span>Description:</span>
				<textarea id="car-f-desc" required maxlength="255" name="description"><?= $car['description'] ?></textarea>
				<span class="err-msg">Description must not be empty.</span>
			</label>
			
			<div><input id="car-f-create" type="submit" value="Update"/></div>
		</form>
		<a href="/cars">Go back</a>
	</div>
</div>