<div class="header">
	<img src="/header/img/logo.png" title="JJPaya Forums">
	<span class="nav">
		<a data-tr="p-main"    href="/main"    class="<?= $current_p('main', true); ?>"></a>
		<a data-tr="p-cars"    href="/cars"    class="<?= $current_p('cars'); ?>"></a>
		<a data-tr="p-shop"    href="/shop"    class="<?= $current_p('shop'); ?>"></a>
		<a data-tr="p-contact" href="/contact" class="<?= $current_p('contact'); ?>"></a>
	</span>
	
	<span class="lang">
		<a data-tr-switch="es" href="javascript:void(0)" title="ES">
			<img src="/header/img/es.png" alt="ES">
		</a>
		<a data-tr-switch="en" href="javascript:void(0)" title="EN">
			<img src="/header/img/en.png" alt="EN">
		</a>
	</span>
	
	<div class="search">
		<input type="text" id="h-search" placeholder="Search cars...">
		<div id="h-autocomplete" class="hidden"></div>
	</div>
	
	<?= require 'navbar_auth.html' ?>
</div>